#!/bin/sh

# Post-installation shell script for Debian package

SOURCEDIR=/var/spool/syna/wlan
PYTHONLIBDIR=/usr/local/syna/lib/python

sudo cp $SOURCEDIR/dhcpcd.conf.* /etc/.
sudo chown root:netdev /etc/dhcpcd.conf.*
sudo chmod 664 /etc/dhcpcd.conf.*

sudo cp $SOURCEDIR/hostapd.conf /etc/hostapd/.
sudo cp $SOURCEDIR/hostapd /etc/default/.

sudo cp $SOURCEDIR/dnsmasq.conf /etc/.

sudo cp $SOURCEDIR/wpa_supplicant.conf.orig /etc/wpa_supplicant/.
sudo chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf.orig

rfkill unblock 0

systemctl is-active dnsmasq.service > /dev/null 2>&1 && sudo systemctl stop dnsmasq.service
rm -f /etc/systemd/system/multi-user.target.wants/dnsmasq.service

systemctl list-unit-files | grep masked | grep hostapd.service > /dev/null 2>&1
if [ $? == 0 ]; then
  sudo systemctl unmask hostapd.service
fi
systemctl is-active hostapd.service > /dev/null 2>&1 && sudo systemctl stop hostapd.service
rm -f /etc/systemd/system/multi-user.target.wants/hostapd.service

sudo mkdir -p $PYTHONLIBDIR/system/wlan
sudo cp $SOURCEDIR/wlan_manager.py $PYTHONLIBDIR/system/wlan/.

systemctl is-active jupyterlab.service > /dev/null 2>&1 && sudo systemctl restart jupyterlab.service
