#!/bin/sh

# Post-installation shell script for Debian package

sudo chown root:netdev /etc/dhcpcd.conf.*
sudo chmod 664 /etc/dhcpcd.conf.*

sudo cp /etc/dnsmasq.conf.ap /etc/dnsmasq.conf

sudo cp /etc/default/hostapd.ap /etc/default/hostapd

sudo chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf.orig

rfkill unblock 0

systemctl is-active dnsmasq.service > /dev/null 2>&1 && sudo systemctl stop dnsmasq.service
rm -f /etc/systemd/system/multi-user.target.wants/dnsmasq.service

systemctl list-unit-files | grep masked | grep hostapd.service > /dev/null 2>&1
if [ $? == 0 ]; then
  sudo systemctl unmask hostapd.service
fi
systemctl is-active hostapd.service > /dev/null 2>&1 && sudo systemctl stop hostapd.service
rm -f /etc/systemd/system/multi-user.target.wants/hostapd.service

systemctl is-active jupyterlab.service > /dev/null 2>&1 && sudo systemctl restart jupyterlab.service
