#!/bin/sh

# Pre-removal shell script for Debian package

sudo cp etc/dhcpcd.conf.orig /etc/dhcpcd.conf
sudo chown root:netdev /etc/dhcpcd.conf
sudo chmod 664 /etc/dhcpcd.conf

sudo cp /etc/dnsmasq.conf.orig /etc/dnsmasq.conf

sudo cp /etc/default/hostapd.orig /etc/default/hostapd

systemctl is-active dnsmasq.service > /dev/null 2>&1 && sudo systemctl stop dnsmasq.service
rm -f /etc/systemd/system/multi-user.target.wants/dnsmasq.service

systemctl is-active hostapd.service > /dev/null 2>&1 && sudo systemctl stop hostapd.service
rm -f /etc/systemd/system/multi-user.target.wants/hostapd.service

systemctl is-active jupyterlab.service > /dev/null 2>&1 && sudo systemctl restart jupyterlab.service
